Cargo.toml
README.md
src/client.rs
src/proto.rs
src/server.rs

Although `futures-util` is used by a majority of downstream users, not depending upon it speeds up the building of tokio-websockets as it can be scheduled earlier.
This removes the following transient dependencies:
* `futures-task`
* `pun-utils`
* `slab`

replace `futures-util` with `futures-core` & `futures-sink`

---

examples/autobahn_client.rs
src/proto.rs

Wrapping the reason in an `Option` is unnecessary as `""` is equivalent to `None`. Likewise, wrapping the close code in an `Option` is unnecessary, when receiving one, as `CloseCode::NoStatusReceived` is equivalent to `None`.

remove duplicate close message empty states

---

src/proto/codec.rs
src/proto/stream.rs
src/proto/types.rs

`Decoder` and `Encoder` implementations should ideally operate on the same types.

Make codec encoder operate on frames

---

src/proto/codec.rs
src/proto/types.rs

By moving to a struct, the internal value becomes private and the only constructor becomes the `TryFrom` implementation. The well-known & sendable close codes are still available as public constants. Close codes returned from the library are available as well.

rework `CloseCode` into a struct

---

src/proto/codec.rs
src/proto/stream.rs
src/utf8.rs
tests/utf8_validation.rs

This refactors the UTF-8 validation into a streaming validator which keeps track of partial codepoints.

Validate UTF-8 in partial continuation frames

---

CHANGELOG.md
src/error.rs
src/proto/codec.rs
src/proto/stream.rs
src/proto/types.rs

99% of users do not care about imposing a different frame and message size limit.

coalesce frame & message limit into payload limit

---

.github/workflows/autobahn.yml
CHANGELOG.md
Cargo.toml
README.md
tests/cancellation_safety.rs
tests/utf8_validation.rs

Speeds up compilation without having to (verbosely) specify `no-default-features = true` and forces users to reason about their optimal RNG & SHA1 impls.
Resolves #11.

empty default features

---

examples/autobahn_client.rs
examples/autobahn_server.rs
src/proto/stream.rs

Alternative to #34 
By logging I observed that we never actually entered the `StreamState` that was supposed to be reached. This moves the state tracking to `queue_frame`, which in turn allows for removing a lot of the checks. Also, the end responsible for responding to a close frame would previously never flush the sink after queueing a response close frame. This is all resolved now.

Fix close sequence, take #2

---

src/upgrade/client_request.rs

Some clients (for example firefox with cloudflare) can send more than 25 headers, which makes them unable to connect.

Increase size of headers buffer

---

src/proto/codec.rs
src/proto/stream.rs
src/proto/types.rs

Fixes an UB when users create a Message::text from invalid UTF-8 and then call Message::as_text on it. This should never be done anyways, so we simply panic if that is the case.

Track whether text message payload was utf8-validated

---

src/lib.rs

The `stdarch_x86_avx512` feature is not defined for other archs.

Enable stdarch_x86_avx512 on nightly for x86_64

---

.github/workflows/ci.yml
Cargo.toml
README.md
src/client.rs
src/error.rs
src/tls.rs

I somehow missed this. We can add this and release 0.8.1 with it.

Add support for rustls-platform-verifier

---

src/proto/types.rs

Unsoundness introduced in d48a281

Handle empty close message reason

---

.github/workflows/ci.yml
Cargo.toml
README.md
src/proto/codec.rs
src/proto/stream.rs
src/proto/types.rs
src/resolver.rs

Some breaking changes for MSRV 1.79 and bytes 1.7 bump while I'm at the breaking changes stuff for a new release...
Why 1.79? Stabilized `split_at_mut_unchecked` which lets us get rid of pointers
Note that this adds `From<Payload>` for `BytesMut` as a public API, yet I think this is less problematic now that the conversion is much cheaper due to `bytes` making it free if the ref counter is 1.

MSRV bump to 1.79 and other breaking changes

---

src/client.rs
src/error.rs
src/tls.rs

This is a great fallback option if no crypto provider is configured via crate features. It allows for `Connector::new` always being available, which is really nice for consumer crates. Sadly, this is a breaking change due to the error enum changes.

Respect rustls default crypto providers

---

Cargo.toml
src/error.rs
src/tls.rs

rustls-native-certs now returns much more fine grained errors. I would consider *some* errors to be acceptable as long as we get some root certificates from *somewhere*, so this will only return a hard error if no certificates were found and webpki-roots cannot be used as a fallback.

Update rustls-native-certs to 0.8

---

src/proto/codec.rs

`BytesMut::reserve` will allocate at least as many bytes as are necessary to later push `additional` bytes. Contrary to how it was assumed in 9d4004f1ecd51d5c101a0ebf5616c892566e0ffc, the behavior before that patch was indeed correct, it is impossible to overallocate with repeating `reserve` calls of finite size, i.e. `reserve(4)` followed by `reserve(4)` will reserve at least 4 bytes (sometimes more so later pushes cause fewer resizes) rather than exactly 8. Playground example for illustration purposes: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=67bb6cef44b4b27f3f809763b7a3c72f
This improves throughput by up to 30% in the decoder with long payloads.

Remove unnecessary capacity substractions when reserving space

---

src/proto/codec.rs

Let's investigate the cases here:
`fin && !opcode.is_control()` can be simplified to `fin && opcode == OpCode::Continuation`, because `!opcode.is_control` only allows Text, Binary and Continuation. If the opcode is Text or Binary and `fin` is true, then we received a single-frame complete message and don't need to touch `fragmented_message_opcode`, so we only need to look at the Continuation case.
`opcode != OpCode::Continuation && !opcode.is_control()` is used to identify the first frame of a multi-frame message here, and is logically equivalent to `opcode == OpCode::Text || opcode == OpCode::Binary`. `!fin` implies `!opcode.is_control()` since control frames must not be fragmented and also is a better way to express the *first* frame aspect of this.
The two can then be merged into a …

Simplify fragmented_message_opcode logic

---

src/proto/codec.rs
src/utf8.rs

While reviewing the code yet again to explore benchmark behavior I stumbled across a few things we should polish.

Minor improvements

---

examples/autobahn_server.rs
examples/echo_server.rs
examples/rustls_server.rs
examples/server.rs
src/server.rs
src/upgrade/client_request.rs
src/upgrade/mod.rs
src/upgrade/server_response.rs

This adds a way to extract the incoming request when accepting a connection.
resolves #78

feat(server): Also return the request when accepting a connection

---

src/client.rs

Otherwise, when using the associated constant, one had to give an explicit value for the resolver generic for it to compile, which is ugly.

Move DISALLOWED_HEADERS to module level

---

.github/workflows/ci.yml
fuzz/fuzz_targets/stream.rs
src/proto/codec.rs
src/proto/types.rs

Don't send invalid closecodes.

---

src/proto/stream.rs
src/proto/types.rs

We can just always store the `Bytes` and use `try_into_mut` when necessary. This lets us drop the `UnsafeCell` and the `PayloadStorage` enum in favor of relying on bytes' correctness when tracking uniqueness.

Get rid of PayloadStorage in favor of using Bytes::try_into_mut

---

.github/workflows/autobahn.yml
Cargo.toml
README.md
autobahn/config/fuzzingclient.json
autobahn/validate.py
examples/autobahn_client.rs
examples/autobahn_server.rs
scripts/autobahn_client_ci.sh
scripts/autobahn_server_ci.sh
src/lib.rs
src/mask.rs
src/utf8.rs
tests/client_is_send.rs

In the SIMD implementations, we convert the `[u8; 4]` to an `i32` anyways, so we can choose between rotating the array or the integer. Rotating the array isn't optimized well by rustc/LLVM as seen in `cargo asm`. On x86, rotating the integer is condensed into just a single instruction, `rol`. We need to load the integer as big-endian to make the rotation possible and then swap byteorder on little-endian targets, which is very efficient on most architectures, e.g. x86 using `bswap`.
<details>
<summary>Full diff of `cargo-asm`:</summary>
```diff
diff --git a/tmp/old.txt b/tmp/new.txt
index 6fd3e7b86..84072182c 100644
--- a/tmp/old.txt
+++ b/tmp/new.txt
@@ -2,19 +2,7 @@
.p2align	4, 0x90
.type	tokio_websockets::mask::imp::frame,@function
tokio_websockets::mask::imp::frame:
-		// …
```

More SIMD optimizations

---

src/mask.rs
src/proto/stream.rs
src/proto/types.rs
src/rand.rs

This saves a bit of memory for every frame queued up. We can remove the option and the length field because the information necessary is stored in the header anyways.
By merging the header and the mask, the client will use 2 I/O slices rather than 3. This may or may not have a positive performance impact.
Finally, we directly write the mask to the header buffer, which simplifies the code a fair bit.

Make encoded frame smaller

---

examples/echo_server.rs
src/proto/codec.rs
src/proto/stream.rs
src/proto/types.rs
src/upgrade/client_request.rs
src/utf8.rs

While auditing this crate I found it uses a lot of unsafe. In just a few minutes I found some bad uses of it, or cases in which the optimizer should easily be able to generate the same exact assembly from checked code. This removes those cases.

Reduce amount of unsafe code

---

Cargo.toml
src/proto/stream.rs
tests/pr102_regression.rs

In some cases poll_close would enter a indefenite loop since the error would stay.
Possibly related to https://github.com/twilight-rs/twilight/issues/2380.

fix(stream): poll_close could in some cases block indefenitely

---

src/proto/stream.rs
src/proto/types.rs

This PR introduces interior mutability for WebSocket limits, enabling applications to adjust them after the handshake. This is useful in scenarios where a connection starts with restrictive limits and later increases them based on application-layer validation of the peer.
Previously, WebSocket limits were immutable once a connection was established, making it difficult to adapt limits dynamically.
Since a WebSocket stream may be passed to a generic function as a `Stream` or `Sink`, type erasure could otherwise prevent access to the limits. Using `Arc` ensures that limits remain accessible and modifiable even when the stream is consumed generically.

Allows accessing websocket limits with interior mutability

---

src/proto/stream.rs
tests/issue106.rs

This fixes an issue where `poll_next` wouldn't always attempt to flush the stream. It will now *always* attempt to do so if there is data available to be sent. There is no problem with this anymore because we now use the same waker that is currently being used for flushing to avoid overwriting the waker.
Fixes #106

Track the flushing waker

---

src/client.rs

ensure flush is completed after writing the websocket upgrade request

---

src/proto/stream.rs

This allows for much more efficient use of poll_write_buf.
I took heavy inspiration from a snippet put together by @conradludgate.

Separate frame queue into new type that implements Buf

---

examples/autobahn_client.rs
examples/rustls_server.rs
src/mask.rs
src/proto/codec.rs
src/proto/stream.rs

Makes the code easier to reason about and gets rid of some duplicate logic.

Rotate masking key in-place

---

examples/rustls_server.rs
src/error.rs
src/tls.rs

Using `ClientConfig::builder` rustls is able to determine a default
crypto provider from its feature flags, side-stepping our
`NoCryptoProviderConfigured` error variant.

Implicitly install default rustls crypto provider

---

.github/workflows/ci.yml

This runs the MSRV cargo powerset checks on loongarch64 and s390x. Ideally we'll also want to run tests on these targets and check for minvers.

Improve and extend CI
