Gelbpunkt/tokio-websockets

- src/proto.rs
The encoder requires knowledge of the current state, as does the `Stream` impl, but since these do not interfere with each other they can share the same copy.
> store only one stream state copy

- README.md
- examples/autobahn_client.rs
- examples/rustls_server.rs
- src/proto.rs
See individual commits' messages
> `poll_close` fixes

- CHANGELOG.md
This needs to be squash merged
> Sync the changelog with latest changes

- .github/workflows/ci.yml
- .gitignore
- Cargo.toml
- benches/Dockerfile
- benches/render.sh
- examples/utf8_benchmark_client.rs
- src/proto/codec.rs
- src/proto/stream.rs
- src/proto/types.rs
This optimises the sink implementation directly.
> Zero-copy send specialization, take 2

- src/client.rs
- src/lib.rs
- src/resolver.rs
> Create a resolver trait

- src/client.rs
- src/proto/stream.rs
- src/server.rs
`FramedRead` is just `Framed` without the write buffer that we don't use.
> Drop unused codec write buffer

- src/proto/types.rs
I don't think we should rename the option.
> Correct documentation for frame_size

- src/client.rs
> Properly resolve IPv6 addresses

- src/proto/stream.rs
This avoids a potentially expensive loop in `poll_ready` and makes the calculation more accurate due to accounting for partial writes.
> Keep track of pending_bytes

- src/proto/stream.rs
- src/proto/types.rs
@finnbear requested something akin to this.
> Make flush threshold configurable

- .github/workflows/ci.yml
- Cargo.toml
- README.md
- src/error.rs
- src/tls.rs
@devanlai please try and let me know if this meets your needs :)
Closes #65
> rustls-bring-your-own-connector feature

- .cargo/config.toml
- README.md
- src/client.rs
- src/lib.rs
- src/mask.rs
TODO: test
CC @famfo @neuschaefer
> Add support for VSX accelerated masking

- src/proto/stream.rs
> Add WebSocketStream::{get_ref, get_mut}

- src/client.rs
>  Move DISALLOWED_HEADERS to module level

- src/proto/stream.rs
> Don't overwrite a pending poll_flush waker

- src/client.rs
Not sure how to handle the TLS case. See #98
> Only include a port if explicitly set

- src/proto/codec.rs
This lets us drop a bunch of trivial unsafe uses and deduplicates code
> Decoder refactors

- .github/workflows/ci.yml
> Fix MSRV checks

- .cargo/config.toml
- README.md
- clippy.toml
- src/lib.rs
- src/mask.rs
> Support SIMD masking on loongarch64

- .github/workflows/ci.yml
- Cargo.toml
- README.md
- src/error.rs
- src/tls.rs
Breaking change, but I think we should slowly start preparing 0.11 with the breaking changes we have been planning for a while now.
> Force users to install a crypto provider for rustls
